from __future__ import annotations

import unicodedata


DEFAULT_HELP_KNOWLEDGE_BASE_VERSION = 2
HELP_STOPWORDS = {
    "aqui",
    "acho",
    "ainda",
    "base",
    "como",
    "com",
    "depois",
    "duvida",
    "dúvida",
    "fica",
    "isso",
    "onde",
    "para",
    "pergunta",
    "por",
    "que",
    "sem",
    "uma",
}


DEFAULT_HELP_KNOWLEDGE_BASE = [
    {
        "id": "cadastrar-evento",
        "titulo": "Cadastrar evento",
        "categoria": "Eventos",
        "pergunta": "Como cadastrar um evento?",
        "resposta": "Cadastre o evento com os dados principais primeiro.",
        "passos": [
            "Abra Eventos.",
            "Clique em Novo evento.",
            "Preencha cliente, data, local e tipo de serviço.",
            "Vincule banheiros, equipamentos e veículos quando souber.",
            "Revise e clique em Salvar.",
        ],
        "palavrasChave": ["evento", "cadastrar", "novo", "data", "local", "logística", "cliente"],
        "rotaRelacionada": "/#events-pane",
        "targetHref": "#events-pane",
        "targetTab": "events-tab",
        "criticidade": "medio",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "cadastrar-cliente",
        "titulo": "Cadastrar cliente",
        "categoria": "Clientes",
        "pergunta": "Como cadastrar um cliente?",
        "resposta": "Cadastre o cliente com o mínimo necessário para operar.",
        "passos": [
            "Abra Clientes.",
            "Clique em Novo cliente.",
            "Informe nome, telefone e endereço.",
            "Escolha tipo de cliente e cobrança.",
            "Salve. Complete os detalhes depois se precisar.",
        ],
        "palavrasChave": ["cliente", "cadastro", "telefone", "endereço", "cpf", "cnpj", "cobrança"],
        "rotaRelacionada": "/#clients-pane",
        "targetHref": "#clients-pane",
        "targetTab": "clients-tab",
        "criticidade": "baixo",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "criar-ordem-servico",
        "titulo": "Criar ordem de serviço",
        "categoria": "Operacional",
        "pergunta": "Como criar ordem de serviço?",
        "resposta": "A ordem de serviço sai pela tela de Eventos.",
        "passos": [
            "Abra Eventos.",
            "Encontre o evento certo.",
            "Confira cliente, data, endereço e itens vinculados.",
            "Clique em OS.",
            "Revise o PDF antes de imprimir ou enviar.",
        ],
        "palavrasChave": ["ordem", "serviço", "os", "pdf", "evento", "imprimir"],
        "rotaRelacionada": "/#events-pane",
        "targetHref": "#events-pane",
        "targetTab": "events-tab",
        "criticidade": "medio",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "registrar-saida-equipamento",
        "titulo": "Registrar saída de equipamento",
        "categoria": "Equipamentos",
        "pergunta": "Como registrar saída de equipamento?",
        "resposta": "Registre saída só depois de conferir o item.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Localize pelo ID ou placa.",
            "Confira evento, cliente e responsável.",
            "Atualize o status apenas se a saída estiver confirmada.",
            "Se houver dúvida, registre pendência ou chame suporte.",
        ],
        "palavrasChave": ["saída", "saida", "equipamento", "banheiro", "placa", "frota", "status"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "alto",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "check-in-equipamento",
        "titulo": "Fazer check-in de equipamento",
        "categoria": "Equipamentos",
        "pergunta": "Como fazer check-in de equipamento?",
        "resposta": "Check-in é a conferência de entrada do item.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Localize o item pelo ID ou placa.",
            "Confira a condição do item.",
            "Confirme cliente ou evento relacionado.",
            "Atualize apenas depois da conferência.",
        ],
        "palavrasChave": ["check-in", "checkin", "entrada", "equipamento", "conferir", "placa"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "alto",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "check-out-equipamento",
        "titulo": "Fazer check-out de equipamento",
        "categoria": "Equipamentos",
        "pergunta": "Como fazer check-out de equipamento?",
        "resposta": "Check-out é a conferência de saída ou retirada.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Confira ID, placa quando houver e responsável.",
            "Veja se o evento está correto.",
            "Atualize o status somente com confirmação.",
            "Se faltar informação, pare e registre pendência.",
        ],
        "palavrasChave": ["check-out", "checkout", "saída", "retirada", "equipamento", "responsável"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "alto",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "registrar-material-extra",
        "titulo": "Registrar material extra enviado",
        "categoria": "Almoxarifado",
        "pergunta": "Como registro material extra enviado para um evento?",
        "resposta": "Material extra enviado deve sair pelo Almoxarifado.",
        "passos": [
            "Abra Almoxarifado.",
            "Encontre o material.",
            "Clique em Saída.",
            "Informe quantidade, evento e observação.",
            "No retorno, registre entrada ou pendência.",
        ],
        "palavrasChave": ["material", "extra", "evento", "pendência", "retorno", "almoxarifado", "saída"],
        "rotaRelacionada": "/#warehouse-pane",
        "targetHref": "#warehouse-pane",
        "targetTab": "warehouse-tab",
        "criticidade": "medio",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "conferir-material-retornado",
        "titulo": "Conferir material retornado",
        "categoria": "Almoxarifado",
        "pergunta": "Como conferir material retornado?",
        "resposta": "Confira o material antes de dar baixa no retorno.",
        "passos": [
            "Abra Almoxarifado.",
            "Localize o material.",
            "Compare quantidade física com o registro.",
            "Registre Entrada se voltou correto.",
            "Se faltou item, registre observação ou pendência.",
        ],
        "palavrasChave": ["material", "retornado", "retorno", "entrada", "conferência", "almoxarifado"],
        "rotaRelacionada": "/#warehouse-pane",
        "targetHref": "#warehouse-pane",
        "targetTab": "warehouse-tab",
        "criticidade": "medio",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "ver-pendencias",
        "titulo": "Ver pendências",
        "categoria": "Rotina",
        "pergunta": "Onde vejo as pendências?",
        "resposta": "As pendências aparecem no resumo inicial.",
        "passos": [
            "Abra o Resumo.",
            "Procure O que precisa de atenção agora.",
            "Comece pelos itens vermelhos.",
            "Depois revise estoque, cobranças e validação.",
        ],
        "palavrasChave": ["pendência", "pendencias", "alerta", "crítico", "resolver", "atenção"],
        "rotaRelacionada": "/#attention-now-panel",
        "targetHref": "#attention-now-panel",
        "targetTab": "summary-tab",
        "criticidade": "baixo",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "falar-suporte-humano",
        "titulo": "Falar com suporte humano",
        "categoria": "Suporte",
        "pergunta": "Como falar com suporte humano?",
        "resposta": "Use suporte quando o assistente não resolver.",
        "passos": [
            "Clique em Chamar suporte.",
            "Explique o problema em uma frase.",
            "Informe a tela onde travou.",
            "Envie o chamado.",
        ],
        "palavrasChave": ["suporte", "ajuda", "travado", "problema", "chamado", "humano"],
        "rotaRelacionada": "/#help-assistant-panel",
        "targetHref": "#help-support-form",
        "targetTab": "",
        "criticidade": "baixo",
        "opcaoInicial": True,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "vincular-cliente-evento",
        "titulo": "Vincular cliente ao evento",
        "categoria": "Eventos",
        "pergunta": "Como coloco o cliente dentro do evento?",
        "resposta": "O cliente precisa estar vinculado ao evento.",
        "passos": [
            "Abra Eventos.",
            "Edite o evento.",
            "Escolha o cliente no campo de clientes.",
            "Salve o evento.",
        ],
        "palavrasChave": ["vincular", "cliente", "evento", "ligar", "associar"],
        "rotaRelacionada": "/#events-pane",
        "targetHref": "#events-pane",
        "targetTab": "events-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "evento-sem-endereco",
        "titulo": "Evento sem endereço",
        "categoria": "Eventos",
        "pergunta": "O evento está sem endereço, o que faço?",
        "resposta": "Endereço incompleto atrapalha rota e PDF.",
        "passos": [
            "Abra o cliente ou evento.",
            "Preencha o endereço completo.",
            "Confira bairro e cidade.",
            "Salve antes de gerar rota ou PDF.",
        ],
        "palavrasChave": ["evento", "endereço", "endereco", "rota", "local", "mapa"],
        "rotaRelacionada": "/#events-pane",
        "targetHref": "#events-pane",
        "targetTab": "events-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "banheiro-luxo-cadastrar",
        "titulo": "Cadastrar banheiro de luxo",
        "categoria": "Banheiros de luxo",
        "pergunta": "Como cadastro banheiro de luxo?",
        "resposta": "Cadastre como equipamento da frota.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Clique para adicionar equipamento.",
            "Escolha Banheiro Luxo ou Trailer Luxo.",
            "Informe ID e placa se houver.",
            "Salve com foto ou observação quando existir.",
        ],
        "palavrasChave": ["banheiro", "luxo", "trailer", "cadastro", "placa", "equipamento"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "baixo",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "banheiro-quimico-cadastrar",
        "titulo": "Cadastrar banheiro químico",
        "categoria": "Banheiros químicos",
        "pergunta": "Como cadastro banheiro químico?",
        "resposta": "Use a tela de Frota e equipamentos.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Adicione um equipamento.",
            "Escolha Banheiro Químico.",
            "Informe o ID do banheiro.",
            "Salve o cadastro.",
        ],
        "palavrasChave": ["banheiro", "químico", "quimico", "cabine", "cadastro", "equipamento"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "baixo",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "equipamento-em-manutencao",
        "titulo": "Colocar equipamento em manutenção",
        "categoria": "Equipamentos",
        "pergunta": "Como marco equipamento em manutenção?",
        "resposta": "Manutenção bloqueia o item para operação.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Localize o item.",
            "Use a ação de manutenção.",
            "Informe o motivo.",
            "Salve apenas se o item realmente não deve sair.",
        ],
        "palavrasChave": ["manutenção", "manutencao", "bloquear", "indisponível", "equipamento"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "alto",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "liberar-equipamento-manutencao",
        "titulo": "Liberar equipamento da manutenção",
        "categoria": "Equipamentos",
        "pergunta": "Como libero equipamento da manutenção?",
        "resposta": "Libere somente quando o item estiver pronto.",
        "passos": [
            "Abra Frota e equipamentos.",
            "Encontre o item em manutenção.",
            "Confirme que foi revisado.",
            "Use a ação de liberar ou retornar ao estoque.",
            "Confira se ficou disponível.",
        ],
        "palavrasChave": ["liberar", "manutenção", "manutencao", "retornar", "disponível"],
        "rotaRelacionada": "/#fleet-pane",
        "targetHref": "#fleet-pane",
        "targetTab": "fleet-tab",
        "criticidade": "alto",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "gerar-rota",
        "titulo": "Gerar rota",
        "categoria": "Rotas",
        "pergunta": "Como gerar rota?",
        "resposta": "Gere rota depois de validar a operação.",
        "passos": [
            "Abra Validar/Gerar.",
            "Escolha o evento se for uma rota específica.",
            "Clique em Validar operação.",
            "Corrija bloqueios vermelhos.",
            "Gere a rota e revise o PDF.",
        ],
        "palavrasChave": ["rota", "gerar", "validar", "pdf", "paradas", "despacho"],
        "rotaRelacionada": "/#operations-pane",
        "targetHref": "#operations-pane",
        "targetTab": "operations-tab",
        "criticidade": "alto",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "validar-operacao",
        "titulo": "Validar operação",
        "categoria": "Rotas",
        "pergunta": "Para que serve validar operação?",
        "resposta": "A validação mostra riscos antes da rota.",
        "passos": [
            "Abra Validar/Gerar.",
            "Clique em Validar operação.",
            "Leia os bloqueios e avisos.",
            "Corrija cadastro, veículo ou equipamento.",
            "Só gere rota quando estiver seguro.",
        ],
        "palavrasChave": ["validar", "operação", "operacao", "bloqueio", "risco", "rota"],
        "rotaRelacionada": "/#operations-pane",
        "targetHref": "#operations-pane",
        "targetTab": "operations-tab",
        "criticidade": "alto",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "baixar-pdf-operacional",
        "titulo": "Baixar PDF operacional",
        "categoria": "Rotas",
        "pergunta": "Onde baixo o PDF da operação?",
        "resposta": "O PDF fica na área de geração de rota.",
        "passos": [
            "Abra Validar/Gerar.",
            "Gere ou revise a rota.",
            "Clique no botão de PDF.",
            "Confira as informações antes de imprimir.",
        ],
        "palavrasChave": ["pdf", "baixar", "imprimir", "rota", "operação", "operacional"],
        "rotaRelacionada": "/#operations-pane",
        "targetHref": "#operations-pane",
        "targetTab": "operations-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "cliente-duplicado",
        "titulo": "Cliente duplicado",
        "categoria": "Clientes",
        "pergunta": "Acho que cadastrei cliente duplicado.",
        "resposta": "Pesquise antes de criar outro cadastro.",
        "passos": [
            "Use a busca global ou abra Clientes.",
            "Procure por nome, telefone ou CPF/CNPJ.",
            "Se já existir, edite o cadastro antigo.",
            "Evite criar outro cliente igual.",
        ],
        "palavrasChave": ["cliente", "duplicado", "repetido", "telefone", "cpf", "cnpj"],
        "rotaRelacionada": "/#clients-pane",
        "targetHref": "#clients-pane",
        "targetTab": "clients-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "cliente-sem-telefone",
        "titulo": "Cliente sem telefone",
        "categoria": "Clientes",
        "pergunta": "O cliente está sem telefone, isso é problema?",
        "resposta": "Telefone ajuda a operação e cobrança.",
        "passos": [
            "Abra Clientes.",
            "Encontre o cliente.",
            "Preencha telefone principal.",
            "Salve antes de fechar cadastro ou evento.",
        ],
        "palavrasChave": ["cliente", "telefone", "contato", "cadastro incompleto"],
        "rotaRelacionada": "/#clients-pane",
        "targetHref": "#clients-pane",
        "targetTab": "clients-tab",
        "criticidade": "baixo",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "registrar-limpeza-cliente",
        "titulo": "Registrar limpeza",
        "categoria": "Clientes",
        "pergunta": "Como registro limpeza de cliente fixo?",
        "resposta": "A limpeza fica no cliente quando for recorrente.",
        "passos": [
            "Abra Clientes.",
            "Encontre o cliente fixo.",
            "Use a ação de limpeza.",
            "Informe a data e observação.",
            "Salve o registro.",
        ],
        "palavrasChave": ["limpeza", "cliente fixo", "recorrente", "semanal", "serviço"],
        "rotaRelacionada": "/#clients-pane",
        "targetHref": "#clients-pane",
        "targetTab": "clients-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "estoque-baixo",
        "titulo": "Ver estoque baixo",
        "categoria": "Almoxarifado",
        "pergunta": "Onde vejo material com estoque baixo?",
        "resposta": "O estoque baixo aparece no Almoxarifado e nas pendências.",
        "passos": [
            "Abra Almoxarifado.",
            "Procure os status baixo ou zerado.",
            "Confira quantidade atual e mínimo.",
            "Registre reposição quando comprar ou receber.",
        ],
        "palavrasChave": ["estoque", "baixo", "zerado", "material", "comprar", "reposição"],
        "rotaRelacionada": "/#warehouse-pane",
        "targetHref": "#warehouse-pane",
        "targetTab": "warehouse-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "registrar-entrada-material",
        "titulo": "Registrar entrada de material",
        "categoria": "Almoxarifado",
        "pergunta": "Como registro entrada de material?",
        "resposta": "Entrada aumenta o saldo do material.",
        "passos": [
            "Abra Almoxarifado.",
            "Localize o material.",
            "Clique em Entrada.",
            "Informe a quantidade.",
            "Salve a movimentação.",
        ],
        "palavrasChave": ["entrada", "material", "almoxarifado", "estoque", "reposição", "reposicao"],
        "rotaRelacionada": "/#warehouse-pane",
        "targetHref": "#warehouse-pane",
        "targetTab": "warehouse-tab",
        "criticidade": "baixo",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "registrar-saida-material",
        "titulo": "Registrar saída de material",
        "categoria": "Almoxarifado",
        "pergunta": "Como registro saída de material?",
        "resposta": "Saída reduz o saldo e deve ter motivo claro.",
        "passos": [
            "Abra Almoxarifado.",
            "Localize o material.",
            "Clique em Saída.",
            "Informe quantidade, evento e observação.",
            "Salve a movimentação.",
        ],
        "palavrasChave": ["saída", "saida", "material", "almoxarifado", "estoque", "evento"],
        "rotaRelacionada": "/#warehouse-pane",
        "targetHref": "#warehouse-pane",
        "targetTab": "warehouse-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "corrigir-status-evento",
        "titulo": "Corrigir status do evento",
        "categoria": "Eventos",
        "pergunta": "Como mudo o status de um evento?",
        "resposta": "Altere status só quando a situação estiver confirmada.",
        "passos": [
            "Abra Eventos.",
            "Encontre o evento.",
            "Escolha o novo status.",
            "Confira se combina com a operação.",
            "Salve.",
        ],
        "palavrasChave": ["status", "evento", "confirmado", "finalizado", "cancelado"],
        "rotaRelacionada": "/#events-pane",
        "targetHref": "#events-pane",
        "targetTab": "events-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "anexar-comprovante",
        "titulo": "Anexar comprovante",
        "categoria": "Operacional",
        "pergunta": "Onde coloco comprovante ou arquivo do cliente?",
        "resposta": "Use a área de anexos do sistema.",
        "passos": [
            "Abra o resumo ou a área de anexos.",
            "Escolha cliente ou evento relacionado.",
            "Envie o arquivo.",
            "Escreva uma observação curta.",
            "Salve.",
        ],
        "palavrasChave": ["anexo", "comprovante", "arquivo", "cliente", "evento", "foto"],
        "rotaRelacionada": "/#attachments-panel",
        "targetHref": "#attachments-panel",
        "targetTab": "summary-tab",
        "criticidade": "baixo",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "buscar-no-sistema",
        "titulo": "Buscar no sistema",
        "categoria": "Rotina",
        "pergunta": "Como acho algo no sistema?",
        "resposta": "Use a busca antes de abrir várias telas.",
        "passos": [
            "Vá para a busca do topo.",
            "Digite nome, telefone, placa, evento ou material.",
            "Use filtros se aparecer muita coisa.",
            "Clique no resultado certo.",
        ],
        "palavrasChave": ["buscar", "busca", "procurar", "telefone", "placa", "evento", "material"],
        "rotaRelacionada": "/#sticky-global-search",
        "targetHref": "#sticky-global-search",
        "targetTab": "summary-tab",
        "criticidade": "baixo",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
    {
        "id": "fechar-dia",
        "titulo": "Fechar o dia",
        "categoria": "Rotina",
        "pergunta": "Como faço fechamento do dia?",
        "resposta": "Feche o dia depois de revisar pendências.",
        "passos": [
            "Abra o resumo inicial.",
            "Revise pendências críticas.",
            "Confira eventos, estoque e financeiro permitido.",
            "Use o fechamento administrativo do dia.",
            "Faça backup quando necessário.",
        ],
        "palavrasChave": ["fechar dia", "fechamento", "backup", "pendência", "rotina"],
        "rotaRelacionada": "/#guided-closeout-panel",
        "targetHref": "#guided-closeout-panel",
        "targetTab": "summary-tab",
        "criticidade": "medio",
        "opcaoInicial": False,
        "seedVersion": DEFAULT_HELP_KNOWLEDGE_BASE_VERSION,
    },
]


def normalize_help_text(value: str | None) -> str:
    text = unicodedata.normalize("NFD", str(value or ""))
    return "".join(char for char in text if unicodedata.category(char) != "Mn").lower()


def score_help_entry(entry: dict, query: str) -> int:
    normalized_query = normalize_help_text(query)
    if not normalized_query:
        return 0
    words = [
        word
        for word in normalized_query.replace("/", " ").replace("-", " ").split()
        if len(word) > 2 and word not in HELP_STOPWORDS
    ]
    fields = [
        str(entry.get("titulo") or ""),
        str(entry.get("categoria") or ""),
        str(entry.get("pergunta") or ""),
        " ".join(str(word) for word in entry.get("palavrasChave") or []),
    ]
    haystack = normalize_help_text(" ".join(fields))
    score = 0
    if normalized_query in haystack:
        score += 6
    for word in words:
        if word in haystack:
            score += 2
        if word in normalize_help_text(entry.get("titulo")):
            score += 2
        if word in normalize_help_text(" ".join(str(item) for item in entry.get("palavrasChave") or [])):
            score += 2
    return score


def search_help_knowledge_base(entries: list[dict], query: str) -> dict | None:
    ranked = sorted(
        ((score_help_entry(entry, query), entry) for entry in entries),
        key=lambda item: item[0],
        reverse=True,
    )
    best_score, best_entry = ranked[0] if ranked else (0, None)
    return best_entry if best_score >= 2 else None


def summarize_help_metrics(metrics: dict, knowledge_base: list[dict], unanswered: list[dict], tickets: list[dict]) -> dict:
    titles = {entry.get("id"): entry.get("titulo") for entry in knowledge_base}
    question_counts = metrics.get("question_counts") if isinstance(metrics.get("question_counts"), dict) else {}
    useful_counts = metrics.get("useful_counts") if isinstance(metrics.get("useful_counts"), dict) else {}
    not_useful_counts = metrics.get("not_useful_counts") if isinstance(metrics.get("not_useful_counts"), dict) else {}
    top_questions = sorted(question_counts.items(), key=lambda item: int(item[1] or 0), reverse=True)[:5]
    return {
        "top_questions": [
            {"id": item_id, "titulo": titles.get(item_id, item_id), "count": count}
            for item_id, count in top_questions
        ],
        "unanswered_total": len(unanswered),
        "unanswered_open": sum(1 for item in unanswered if item.get("status") in {"nova", "em_analise", "em análise"}),
        "support_clicks": int(metrics.get("support_clicks") or 0),
        "support_tickets_total": len(tickets),
        "support_tickets_open": sum(1 for item in tickets if item.get("status") not in {"resolvido", "resolvida"}),
        "useful_total": sum(int(value or 0) for value in useful_counts.values()),
        "not_useful_total": sum(int(value or 0) for value in not_useful_counts.values()),
    }
